import XCTest
@testable import yournextbg

/// Cross-platform parity: every case in `scoring-parity.json` must
/// produce the same distance + similarity value (to 6 decimal places)
/// from our Swift `Scoring` implementation.
///
/// The fixture is generated by `ios/scripts/generate-scoring-fixtures.mjs`,
/// which mirrors `src/lib/scoring/`. When the TS engine changes, the
/// generator must be updated and rerun, and Android's parity test
/// regenerates against the same JSON.
final class ScoringParityTests: XCTestCase {

    struct ParityCase: Decodable {
        let a: String
        let b: String
        let lens: String
        let distance: Double
        let similarity: Double
    }

    struct ParityGame: Decodable {
        let id: String
        let scores: [Double]
    }

    struct ParityFixture: Decodable {
        let axisOrder: [String]
        let lenses: [String]
        let games: [ParityGame]
        let cases: [ParityCase]
    }

    func testParity() throws {
        let bundle = Bundle(for: Self.self)
        // Resources copied as a folder reference live under the bundle root.
        guard let url = bundle.url(forResource: "scoring-parity", withExtension: "json")
                ?? bundle.url(forResource: "scoring-parity", withExtension: "json", subdirectory: "Fixtures") else {
            return XCTFail("scoring-parity.json not in test bundle")
        }
        let data = try Data(contentsOf: url)
        let fix = try JSONDecoder().decode(ParityFixture.self, from: data)

        // Axis order must match the Swift enum, or every distance is off.
        XCTAssertEqual(fix.axisOrder, AxisKey.allCases.map { $0.rawValue },
                       "axis order in fixture has drifted from AxisKey")

        // Build lookup table of vectors.
        let vectors: [String: ScoreVector] = Dictionary(
            uniqueKeysWithValues: fix.games.map { ($0.id, ScoreVector($0.scores)) }
        )

        for c in fix.cases {
            guard let a = vectors[c.a], let b = vectors[c.b] else {
                XCTFail("case references unknown vector: \(c.a) or \(c.b)")
                continue
            }
            guard let lens = LensKey(rawValue: c.lens) else {
                XCTFail("unknown lens: \(c.lens)")
                continue
            }
            let dist = Scoring.weightedDistance(a, b, lens: lens)
            let sim = Scoring.similarity(a, b, lens: lens)

            XCTAssertEqual(
                dist, c.distance, accuracy: 1e-6,
                "distance mismatch for \(c.a) vs \(c.b) under \(c.lens)"
            )
            XCTAssertEqual(
                sim, c.similarity, accuracy: 1e-6,
                "similarity mismatch for \(c.a) vs \(c.b) under \(c.lens)"
            )
        }
    }

    // MARK: spot-checks (cheap to read; document the invariants)

    func testIdenticalVectorsHaveZeroDistanceUnderEveryLens() {
        let v = ScoreVector([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])
        for lens in LensKey.allCases {
            XCTAssertEqual(Scoring.weightedDistance(v, v, lens: lens), 0)
            XCTAssertEqual(Scoring.similarity(v, v, lens: lens), 1)
        }
    }

    func testMaximallyDifferentVectorsHitMaxDistance() {
        let lo = ScoreVector(Array(repeating: 0.0, count: AXIS_COUNT))
        let hi = ScoreVector(Array(repeating: 10.0, count: AXIS_COUNT))
        for lens in LensKey.allCases {
            let d = Scoring.weightedDistance(lo, hi, lens: lens)
            XCTAssertEqual(d, Scoring.maxDistance(lens: lens), accuracy: 1e-9)
            XCTAssertEqual(Scoring.similarity(lo, hi, lens: lens), 0, accuracy: 1e-9)
        }
    }

    func testAxisDeltasSortedDescending() {
        let a = ScoreVector([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2])
        let b = ScoreVector([10, 8, 6, 4, 2, 0, 1, 2, 3, 4, 1, 2])
        let deltas = Scoring.axisDeltas(a, b)
        for i in 0..<(deltas.count - 1) {
            XCTAssertGreaterThanOrEqual(deltas[i].delta, deltas[i + 1].delta)
        }
    }
}
